<?php

namespace ContainerKl810gv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutlierControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OutlierController' shared autowired service.
     *
     * @return \App\Controller\OutlierController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/OutlierController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/OutlierProcessorService.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/OutlierRepository.php';

        $a = ($container->services['.container.private.session'] ?? $container->load('get_Container_Private_SessionService'));

        $container->services['App\\Controller\\OutlierController'] = $instance = new \App\Controller\OutlierController(new \App\Service\OutlierProcessorService($a, new \App\Repository\OutlierRepository()), $a);

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\OutlierController', $container));

        return $instance;
    }
}
