<?php

namespace ContainerPxHOzMy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImportController' shared autowired service.
     *
     * @return \App\Controller\ImportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ImportController.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ExchangeRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SplFileInfoWrapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        $container->services['App\\Controller\\ImportController'] = $instance = new \App\Controller\ImportController(new \App\Repository\ExchangeRepository(($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), new \App\Service\SplFileInfoWrapper('var/import.csv')));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'session' => ['privates', '.session.deprecated', 'get_Session_DeprecatedService', true],
        ], [
            'doctrine' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'session' => '.session.deprecated',
        ]))->withContext('App\\Controller\\ImportController', $container));

        return $instance;
    }
}
