<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2fj6ZA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2fj6ZA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF2fj6ZA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF2fj6ZA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF2fj6ZA\App_KernelDevDebugContainer([
    'container.build_hash' => 'F2fj6ZA',
    'container.build_id' => 'e568a500',
    'container.build_time' => 1710674628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2fj6ZA');
