<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxHOzMy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxHOzMy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxHOzMy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxHOzMy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxHOzMy\App_KernelDevDebugContainer([
    'container.build_hash' => 'PxHOzMy',
    'container.build_id' => '81ef3be2',
    'container.build_time' => 1710670865,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxHOzMy');
